#pragma once

enum ECommand : int
{
	// commands for robot
	RC_CMD_MOVE_FORWARD,
	RC_CMD_MOVE_BACKWARD,
	RC_CMD_MOVE_RIGHT,
	RC_CMD_MOVE_LEFT,
	RC_CMD_STOP_MOVEMENT,
	RC_CMD_ROTATE_RIGHT,
	RC_CMD_ROTATE_LEFT,
	RC_CMD_ARM_PLATFORM_ROTATE,

	// other service commands
	RC_CMD_FUNCTION,
	RC_CMD_BEGIN,
	RC_CMD_END,
	RC_CMD_MOVE,
	RC_CMD_ROTATE,
	RC_CMD_STOP,
	RC_CMD_FWD,
	RC_CMD_BCW,
	RC_CMD_RIGHT,
	RC_CMD_LEFT,
	RC_CMD_WAIT,
	RC_CMD_ARM
};